# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3141be6d7dea986bd444da219367d71b1e0b7535a3c39dbb0e890661f929e1cfed6fbc11f1ea6ae58bcd9f04ae683ce6b3e2bd57f6a4b45406fcc396c3acaede

test:
  secret_key_base: c0b7a8ba568ead201386d775e9987979103870a37008842421f0cf20275660cec357836677d78cb55abd8a951e7c69ee1e9b50d9bb11a39952d91e8e136ead33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
